### ISSUE TITLE
ModuleNotFoundError: No module named 'third_party.structg'

### ISSUE THREAD

**Issue by TreemanCHou** [berlino/grammar-prompting#2]
I installed the code following the README.md and met this error. Is there some code missing here

**Comment by berlino** [comment]
ah, sry

There is an unnecessary import. Just removed it. Let me if there is still issue

**Comment by TreemanCHou** [comment]
> ah, sry
> 
> There is an unnecessary import. Just removed it. Let me if there is still issue

Thanks for reply ! But still has some issues  
It was imported in `neural_lark/dataset.py` .
```python
from third_party.structg.eval import check_equiv         
```

and in line 283-290 I find the usage of the `check_equiv` (288) :
```python
    for prediction_counter, example in zip(predictions, examples):
        prediction = counter2pred(prediction_counter)
        if prediction:
            prediction = unnaturalize(prediction)
            target = unnaturalize(example.target)
>          if check_equiv(prediction, target):
                counter += 1
    return counter / len(predictions)
```

How to deal with these code 🥹

**Comment by berlino** [comment]
basically, check_equiv is a function used to evaluate on other datasets I was trying. You should notice that the outer function evaluate_dfa is actually never used. So you can ignore it

**Comment by berlino** [comment]
feel free to reopen the issue
