### ISSUE TITLE
retro_star

### ISSUE THREAD

**Issue by wentao228** [berlino/grammar-prompting#4]
Hi Bailin,

When I run pip install -e third_party/retro_star/retro_star/packages/mlp_retrosyn/, I noticed that the third_party directory does not contain the retro_star folder. Could you please provide it?

Many thanks!

**Comment by ZhaoningYu1996** [comment]
Hi wentao228,

I am facing the same issue.
How did you solve it?

Thank you!

**Comment by wentao228** [comment]
Hi Zhaoning, you can download it from https://github.com/binghong-ml/retro_star and put it in the retro_star folder.
